//
// Created by scacc on 05/08/2021.
//

#ifndef ELECTRICISSUESIMULATOR_TISSUEVIEWMODEL_H
#define ELECTRICISSUESIMULATOR_TISSUEVIEWMODEL_H

#include <jni.h>


#endif //ELECTRICISSUESIMULATOR_TISSUEVIEWMODEL_H
